user/models.py
from mongoengine import signals

from application import db
from utilities.common import uts_now_ts as now


class User(db.Document):
    '''
    Adding User model on top of
    MongoDb.
    The Definition of fields are as follows:
    '''
    username = db.StringField(db_field='u', required=True, unique=True)
    password = db.StringField(db_field='p', required=True)
    email = db.StringField(db_field='e', required=True, unique=True)
    first_name = db.StringField(db_field='fn', max_length=50)
    last_name = db.StringField(db_field='ln', max_length=50)
    created = db.IntField(db_field='c', default=now)
    bio = db.StringField(db_field='b', max_length=160)

    @classmethod
    def pre_save(cls, sender, document, **kwargs):
        document.username = document.username.lower()
        document.email = document.email.lower()

    '''
    Creating Index for the User Model.
    the minus(-) in front of created index
    means the created index is sorted descending. 
    '''
    meta = {
        'indexes': ['username', 'email', '-created']
    }

signals.pre_save.connect(User.pre_save, sender=User)

user/forms.py
from flask_wtf import Form
from wtforms import validators, StringField, PasswordField
from wtforms.widgets import TextArea
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError
from user.models import User
import re


class BaseUserForm(Form):
    '''
    BaseUserForm class
    '''
    first_name = StringField('First Name', [validators.DataRequired()])
    last_name = StringField('Last Name', [validators.DataRequired()])
    email = EmailField('Email Address', [
        validators.DataRequired(),
        validators.Email()
    ])
    username = StringField('Username', [
        validators.required(),
        validators.length(min=4, max=25)
    ])
    bio = StringField('Bio',
                      widget=TextArea(),
                      validators=[validators.length(max=160)]
                      )


class RegisterForm(BaseUserForm):
    '''
    RegisterForm which extends BaseUserForm Class
    '''
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Password Must Match'),
        validators.length(min=4, max=80)
    ])
    confirm = PasswordField('Repeat Password')

    def validate_username(form, field):
        if User.objects.filter(username=field.data).first():
            raise ValidationError("Username Already Exists")
        if not re.match('^[a-zA-Z0-9_-]{4,25}$', field.data):
            raise ValidationError('Invalid Username')

    def validate_email(form, field):
        if User.objects.filter(email=field.data).first():
            raise ValidationError("Email Already Exists")



class LoginForm(Form):
    username = StringField('Username', [
        validators.DataRequired(),
        validators.length(min=4, max=25)
    ])
    password = PasswordField('Password', [
        validators.DataRequired(),
        validators.length(min=4, max=80)
    ])

class EditForm(BaseUserForm):
    pass

user/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for, abort
from forms import BaseUserForm, RegisterForm, EditForm
import bcrypt

from user.models import User
from user.forms import RegisterForm, LoginForm

# Creating user_app Blueprint
user_app = Blueprint('user_app', __name__)


@user_app.route('/register', methods=['Get', 'POST'])
def register():
    '''
    Registration
    :return: resgister.html Template
    '''
    form = RegisterForm() # RegisterForm Class Instantiating
    if form.validate_on_submit():
        salt = bcrypt.gensalt() # Generating Salt
        hashed_password = bcrypt.hashpw(form.password.data.encode('utf-8'), salt) # Generating Hashed Password
        # Instantiating The User Model Class
        # These are Database Fields which are
        # defined in the user.models
        user = User(
            username=form.username.data,
            password=hashed_password,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data
        )
        user.save() # Saves the record to mongodb
        return 'User Registered'
    return render_template('user/register.html', form=form)


@user_app.route('/login', methods=['Get', 'POST'])
def login():
    '''
    Login
    :return:
    '''
    form = LoginForm() # LoginForm Class Instantiating
    error = None
    # if there is a 'next' argument in request
    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next')
    if form.validate_on_submit():
        # Instantiating User Class and Querying the Database
        user = User.objects.filter(username=form.username.data).first()
        if user:
            # Checking the input password with the one in the Database
            # All The Passwords must be encoded to UTF-8
            if bcrypt.hashpw(form.password.data.encode('utf-8'), user.password.encode('utf-8')) == user.password.encode('utf-8'):
                session['username'] = form.username.data # Session Variable
                # Processing next
                if 'next' in session:
                    next = session.get('next')
                    session.pop('next')
                    return redirect(next)
                else:
                    return 'User Logged in'
            else:
                user = None
        if not user:
            error = 'Incorrect Credentials'

    return render_template('user/login.html', form=form, error=error)

@user_app.route('/logout', methods=['Get', 'POST'])
def logout():
    session.pop('username')
    return redirect(url_for(user_app.login))

@user_app.route('/<username>', methods=['Get', 'POST'])
def profile(username):
    edit_profile = False
    user = User.objects.filter(username=username).first()
    if session.get('username') and user.username == session.get('username'):
        edit_profile = True
    if user:
        return render_template('user/profile.html', user=user, edit_profile=edit_profile)
    else:
        abort(404)


@user_app.route('/edit', methods=['Get', 'POST'])
def edit():
    error = None
    message = None
    user = User.objects.filter(username=session.get('username')).first()
    if user:
        form = EditForm(obj=user)
        if form.validate_on_submit():
            if user.username != form.username.data:
                if User.objects.filter(username=form.username.data.lower()).first:
                    error = 'Username Already Existes'
                else:
                    session['username'] = form.username.data.lower()
                    form.username.data = form.username.data.lower()
        if user.email != form.email.data:
            if User.objects.filter(email=form.email.data.lower()).first():
                error = 'Email Already Exists'
            else:
                form.email.data = form.email.data.lower()
        if not error:
                form.populate_obj(user)
                user.save()
                message = 'Profile Updated'
        return render_template('user/edit.html', form=form, error=error, message=message)
    if not user:
        abort(404)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% include "navbar.html" %}


    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

    {% block header %}{% endblock %}
</head>
<body>

<div class="container">

    {% block content %}{% endblock %}

    <div class="col-md-offset-3 col-md-6">
        <hr/>
        <footer>
            &copy; copyright 2019 HosseinDavoodi
        </footer>
    </div>

</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block end_body_js %}{% endblock %}

</body>
</html>

templates/feed/_feed_messages.html
{% macro render_feed_message(message) %}
<div class="media">
  <div class="media-left">
    <a href="{{ url_for('user_app.profile', username=message.from_user.username) }}">
      <img class="media-object" src="{{ message.from_user.profile_imgsrc('sm') }}" width="50" height="50" alt="{{ message.from_user.username }}">
    </a>
  </div> <!-- media-left -->
  <div class="media-body">
    <div class="media-user-pane">
      <span class="media-user"><a href="{{ url_for('user_app.profile', username=message.from_user.username) }}">{{ message.from_user.first_name }} {{ message.from_user.last_name }}</a></span>
      {% if message.to_user %}
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span class="media-user"><a href="{{ url_for('user_app.profile', username=message.to_user.username) }}">{{ message.to_user.first_name }} {{ message.to_user.last_name }}</a></span>
      {% endif %}
    </div>
    <div class="media-text">{{ message.text_linkified|safe }}</div>
    {% if message.images %}
    <div class="media-images">
    {% for image in message.images %}
      <img class="img-thumbnail" src="{{ message.post_imgsrc(image.ts, 'xlg') }}" width="{{ image.w }}" height="200" alt="" />
    {% endfor %}
    </div> <!-- media-images -->
    {% endif %}
    <div class="media-footer">
      <a href="{{ url_for('feed_app.message', message_id=message.id) }}" class="media-timestamp">
        {{ message.human_timestamp }}
      </a> -
      <a href="{{ url_for('feed_app.message', message_id=message.id) }}#comment-form">Comment</a>
      {% if message.comments %}({{ message.comments.count() }}){% endif %}
       - <a href="{{ url_for('feed_app.like_message', message_id=message.id) }}">Like</a>
      {% if message.likes %}
      <div class="media-footer-likes">
          <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
          {% set comma = joiner(", ") %}
          {% for like in message.likes %}{{ comma() }}<a href="{{ url_for('user_app.profile', username=like.from_user.username) }}">{{ like.from_user.username }}</a>{% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div> <!-- media -->
{% endmacro %}

templates/includes/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
    {{ field.label }}
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
    <ul class="text-danger">
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endmacro %}

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('user_app.profile', username=session.username) }}">
                <img alt="flaskbook logo" width="82" height="20"
                     src="{{ url_for('static', filename='assets/flaskbook-logo-sm.png') }}">
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if session.username %}
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        @{{ session.username }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('user_app.profile', username=session.username) }}">View profile</a></li>
                        <li><a href="{{ url_for('user_app.edit') }}">Edit profile</a></li>

                    </ul>
                </li>
                <li>
                    <a href="{{ url_for('user_app.logout') }}" class="navbar-link">Logout</a></p>
                </li>
                {% else %}
                <li>
                    <a href="{{ url_for('user_app.login') }}" class="navbar-link">Login</a></p>
                </li>
                <li>
                    <a href="{{ url_for('user_app.register') }}" class="navbar-link">Register</a></p>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/user/_rel_button.html
{% macro rel_button(rel, user) %}

{% if rel == "SAME" %}
<a href="{{ url_for('.edit') }}" role="button" class="btn btn-default">
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    Edit profile
</a>
{% endif %}

{% if rel == None %}
<a href="{{ url_for('relationship_app.add_friend', to_username=user.username) }}" role="button"
   class="relationship-add-friend btn btn-default">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Friend
</a>
<a href="{{ url_for('relationship_app.block', to_username=user.username) }}" role="button" class="btn btn-default">
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Block
</a>
{% endif %}

{% if rel == "BLOCKED" %}
<a href="{{ url_for('relationship_app.unblock', to_username=user.username) }}" role="button"
   class="relationship-blocked btn btn-danger">
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <span id="relationship-label">Blocked</span>
</a>
{% endif %}

{% if rel == "FRIENDS_APPROVED" %}
<a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button"
   class="relationship-friends btn btn-primary">
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> <span id="relationship-label">Friends</span>
</a>
{% endif %}

{% if rel == "FRIENDS_PENDING" %}
<a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button"
   class="relationship-friends-requested btn btn-primary">
    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span
        id="relationship-label">Friendship Requested</span>
</a>
{% endif %}

{% if rel == "REVERSE_FRIENDS_PENDING" %}
<a href="{{ url_for('relationship_app.add_friend', to_username=user.username) }}" role="button"
   class="relationship-reverse-friends-requested btn btn-primary">
    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span
        id="relationship-label">Accept Friendship</span>
</a>
<a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button"
   class="relationship-reverse-friends-cancel btn btn-default">
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <span
        id="relationship-label">Deny Friendship</span>
</a>
{% endif %}

{% if rel == "REVERSE_BLOCKED" %}
<a href="#" class="relationship-reverse-blocked"></a>
{% endif %}
{% endmacro %}

{% macro rel_js() %}
<script type="text/javascript">
$(document).ready(function(){
  $('.relationship-friends').mouseover(function() {
    $(this).find('.relationship-label').text('Unfriend');
    $(this).attr("class", "btn btn-default");
  }).mouseout(function(){
    $(this).find('.relationship-label').text('Friends');
    $(this).attr("class", "btn btn-primary");
  });            
});
$(document).ready(function(){
  $('.relationship-blocked').mouseover(function() {
    $(this).find('.relationship-label').text('Unblock');
    $(this).attr("class", "btn btn-default");
  }).mouseout(function(){
    $(this).find('.relationship-label').text('Blocked');
    $(this).attr("class", "btn btn-danger");
  });            
});
$(document).ready(function(){
  $('.relationship-friends-requested').mouseover(function() {
    $(this).find('.relationship-label').text('Cancel Friend Request');
    $(this).attr("class", "btn btn-danger");
  }).mouseout(function(){
    $(this).find('.relationship-label').text('Friendship Requested');
    $(this).attr("class", "btn btn-primary");
  });            
});

</script>
{% endmacro %}

templates/user/edit.html
{% extends "base.html" %}

{% block title %}Edit profile{% endblock %}

{% block content %}

<div class="row">

    <div class="col-md-offset-3 col-md-6">

        <h3>Edit Profile</h3>

        {% if error %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endif %}

        {% if message %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
        {% endif %}

        {% from "includes/_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('.edit')}}" role="form" enctype="multipart/form-data">

            {{ form.hidden_tag() }}
            {{ render_field(form.first_name, class='form-control') }}
            {{ render_field(form.last_name, class='form-control') }}

            {{ render_field(form.username, class='form-control') }}
            {{ render_field(form.email, class='form-control') }}

            {{ render_field(form.bio, maxlength="160", rows="3", class='form-control') }}

            <button type="submit" class="btn btn-default">Save</button>

        </form>

    </div>

</div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}


<div class="row">

    <div class="col-md-offset-3 col-md-6">

        <h3>User Login</h3>

        {% if error %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endif %}

        {% from "includes/_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('.login')}}" role="form">

            {{ form.hidden_tag() }}

            {{ render_field(form.username, class='form-control') }}
            {{ render_field(form.password, **{"class": "form-control", "aria-described-by": "passwordHelpBlock"}) }}

            <span id="passwordHelpBlock" class="help-block"><a
                    href="{{ url_for('.login') }}">Forgot password?</a></span>

            <button type="submit" class="btn btn-default">Login</button>

        </form>

    </div>

</div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}
{% from "user/_rel_button.html" import rel_button, rel_js %}

{% block title %}{{ user.username }} - Profile{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}

<div class="row">

  <div class="col-md-3">

    <img class="media-object" src="//placehold.it/200x200" width="200" height="200" alt="{{ user.username }}">

    <h3 class="profile-fullname">{{ user.first_name }} {{ user.last_name }}</h3>
    <h3 class="profile-username"><a href="{{ url_for('user_app.profile', username=user.username) }}" />@{{ user.username }}</a></h3>

  </div> <!-- col-md-3 -->

  <div class="col-md-9">

    <div id="friends-toolbar" class="row">
      <div class="btn-toolbar pull-right" role="toolbar" aria-label="friends-toolbar">
        <div class="btn-group" role="group" aria-label="friends-toolbar-buttons">
          {% if edit_profile %}
            <a href="{{ url_for('.edit') }}" role="button" class="btn btn-default">
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span>
              Edit Profile
            </a>
          {% else %}
          <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-ok" aria-hidden="true"> Friends</span>
          </button>
          {% endif %}

        </div> <!-- btn-group -->
      </div> <!-- btn-toolbar -->

    </div> <!-- friends-toolbar -->

    <div class="row">

      {% if not friends_page %}

      <div class="col-md-9">

        {% if logged_user and (rel == "FRIENDS_APPROVED" or logged_user == user) %}
        <!-- post text input -->
        <div class="row feed-message">
          {% if error %}
          <div class="alert alert-danger" role="alert">{{ error }}</div>
          {% endif %}

          {% from "_formhelpers.html" import render_field %}
          <form method="POST" action={{ url_for('feed_app.add_message') }} role="form">
            {{ form.hidden_tag() }}

            <div class="form-group">
              {{ form.images(class='form-control') }}
              {{ form.post(class='form-control', rows=3) }}
            </div>

            <input type="hidden" name="to_user" value="{{ user.username }}" />
            <button type="submit" class="btn btn-primary pull-right">Post</button>

          </form>
          </div> <!-- feed-message -->
          <!-- post text input -->
          {% endif %}

          {% from "feed/_feed_messages.html" import render_feed_message %}
          {% for message in profile_messages %}
            {{ render_feed_message(message) }}
          {% endfor %}

      </div> <!-- col-md-9 -->

      <div class="col-md-3"> <!-- Friends side bar -->

        <h4><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          <a href="{{ url_for('user_app.profile', username=user.username) }}">Friends</a>
        <span class="badge">{{ friends_total }}</span></h4>

        {% for friend in friends %}
        <div class="media">
          <div class="media-left">
            <a class="img-thumnbnail" href="{{ url_for('.profile', username=friend.to_user.username) }}">
              <img class="media-object" src="{{ friend.to_user.profile_imgsrc('sm') }}" width="50" height="50" alt="{{ friend.to_user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>{{ friend.to_user.first_name }}<br />
              <a href="{{ url_for('.profile', username=friend.to_user.username) }}">@{{ friend.to_user.username }}</a>
            </p>
          </div>
        </div> <!-- media -->
        {% endfor %}

      </div> <!-- Friends side bar -->

      {% else %}

      <div class="col-md-12"> <!-- == Friend list == -->

        <div class="row">

          {% for friend in friends.items %}

            <div class="col-md-3 friend-grid-user">
              <div class="friend-grid-user-image">
                <a class="img-thumbnail" href="{{ url_for('.profile', username=friend.to_user.username) }}">
                  <img src="{{ friend.to_user.profile_imgsrc('lg') }}" width="75" alt="{{ friend.to_user.username }}">
                </a>
              </div>
              <div class="friend-grid-user-data">
                <h4 class="profile-fullname">{{ friend.to_user.first_name }} {{ friend.to_user.last_name }} </h5>
                <h5 class="profile-username"><a href="{{ url_for('.profile', username=friend.to_user.username) }}">@{{ friend.to_user.username }}</a></h4>
              </div>
              <div class="friend-grid-user-friends-button">
                {{ rel_button(friend.is_friend(logged_user), friend.to_user) }}
              </div>
            </div> <!-- col-md-3 -->

          {% endfor %}

        </div> <!-- row -->

      </div> <!-- col-md-12 -->

      <div class="profile-friends-pagination col-md-12"> <!-- == Pagination == -->

        <div class="row">

          <div class="col-md-6 pull-left">
          {% if friends.has_prev %}
          <a role="button" class="btn btn-primary" href="{{ url_for('.profile-friends-page', username=user.username, friends_page_number=friends.prev_num) }}">< Previous</a>
          {% endif %}
          </div> <!-- col-md-6 -->

          <div class="col-md-6 pull-right">
          {% if friends.has_next %}
          <a class="btn btn-primary" href="{{ url_for('.profile-friends-page', username=user.username, friends_page_number=friends.next_num) }}">Next ></a>
          {% endif %}
          </div> <!-- col-md-6 -->

        </div> <!-- row -->

      </div>

      {% endif %}

    </div> <!-- row -->

  </div> <!-- col-md-9 -->

</div>
{% endblock %}

{% block end_body_js %}
{{ rel_js() }}
{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}


<div class="row">

    <div class="col-md-offset-3 col-md-6">

        <h3>Registration</h3>

        {% from "includes/_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('.register')}}" role="form">

            {{ form.hidden_tag() }}

            {{ render_field(form.first_name, class='form-control') }}
            {{ render_field(form.last_name, class='form-control') }}

            {{ render_field(form.username, class='form-control') }}
            {{ render_field(form.email, class='form-control') }}

            {{ render_field(form.password, class='form-control') }}
            {{ render_field(form.confirm, class='form-control') }}

            <button type="submit" class="btn btn-default">Register</button>

        </form>

    </div>

</div>
{% endblock %}